DROP TABLE IF EXISTS bubble, jug;


CREATE TABLE jug (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL
);


CREATE TABLE bubble (
  jug_id integer REFERENCES jug(id) DEFERRABLE INITIALLY DEFERRED,
  created timestamptz NOT NULL default now()
);

INSERT INTO jug (name) VALUES ('mead');
