# Generated by Django 3.0.7 on 2020-06-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE bubble ALTER COLUMN created SET DEFAULT now();")
    ]
